SITE: "cordoba"
SEED: 1234
percentile_to_load: "90p"

paths:
  file_g500: "/gpfs/scratch/bsc32/bsc167965/data/era5/lagged_anomalies/g500_1x1_lagged_standarized_anomalies.nc"
  file_g200: "/gpfs/scratch/bsc32/bsc167965/data/era5/lagged_anomalies/g200_1x1_lagged_standarized_anomalies.nc"
  file_psl: "/gpfs/scratch/bsc32/bsc167965/data/era5/lagged_anomalies/psl_1x1_lagged_standarized_anomalies.nc"
  file_CO2: "/gpfs/scratch/bsc32/bsc167965/data/daily_co2_JJA.nc"
  file_local_scale: "/gpfs/scratch/bsc32/bsc167965/data/era5land/lagged_anomalies_and_event_detection/90p_cordoba_lagged_standarized_anomalies_and_extreme_detection.nc"

  base_folder: "/gpfs/scratch/bsc32/bsc214253/mockdata"

  model_dir: "/gpfs/scratch/bsc32/bsc214253/data/test_train_n_shap_dilation"
  results_dir: "/gpfs/scratch/bsc32/bsc214253/results"
  shap_dir: "/gpfs/scratch/bsc32/bsc214253/results/shap"

epoch_config:
  epochs: 75

dataset_config:
  variables_era5: ["g500", "g200", "psl"]
  variables_era5land: ["swvl1", "swvl2", "swvl3"]
  start_date: "1950-01-01"

site_hypms:
  lr: 1e-4
  w_decay: 0.01
  batch_size: 32
  extreme_weights_ctt: 1
  nonextreme_weights_ctt: 1
  minority_weight_multiplier: 1.0

save_paths:
  model_dir: "/gpfs/scratch/bsc32/bsc214253/data/test_train_n_shap_dilation"
  results_dir: "/gpfs/scratch/bsc32/bsc214253/results"
